import type { CategoryModel } from '../categories/category.model';
import type { CommuneModel, DistrictModel, ProvinceModel } from '../region/region.model';

interface SatLoModel {
  id: number;
  tennhan: string;
  diadiem: string;
  tacdong: string;
  ten_tinh: string;
  trangthai: string;
  ghichu: string;
  thoigian: string;
  giaiphap: string;
  chieusau: string;
  chieurong: string;
  huyenref: string;
  xaref: string;
  nguonvon: string;
  baovekhuvuc: string;
  vatlieu: string;
  mucdoondinh: string;
  khananggayboi: string;
  hinhthuc: string;
  soluongmatcat: string;
  cokehoachhotro: string;
  ketcau: string;
  kinhphi_trunguong: string;
  kinhphi_diaphuong: string;
  nguonvon_diaphuong: string;
  xulydiaphuong: string;
  chieudai: number;
  tongkinhphi?: number;
  kinhphi?: number;
  lon: number;
  lat: number;
  province_code: string;
  district_code: string;
  commune_code: string;
  loaidiadiem: number;
  thuocbien: number;
  thuocsong: number;
  namxaydung: number;
  namhoanthanh: number;
  tinhtrang_satlo_id: number;
  duyet: boolean;
  read: boolean;
  duyet_dp: boolean;
  iscanhbao: boolean;
  province: ProvinceModel;
  district: DistrictModel;
  commune: CommuneModel;
  dmTinhTrang: CategoryModel;
}

export type { SatLoModel };
